# Generated by Django 3.0.3 on 2020-03-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
