# Generated by Django 3.0.3 on 2020-03-16 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestFirstName', models.CharField(max_length=255)),
                ('guestLastName', models.CharField(max_length=255)),
                ('CheckIn', models.DateField(default=django.utils.timezone.now, null=True)),
                ('CheckOut', models.DateField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(default='UnBooked', max_length=10, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
